apiVersion: v1
kind: Service
metadata:
  labels:
    app: crm
    stack: echo
    interface: rest
    language: golang
  name: crm
spec:
  ports:
    - name: http
      port: 9999
      protocol: TCP
      targetPort: 9999
  selector:
    app: crm