apiVersion: v1
kind: Service
metadata:
  labels:
    app: shopping-cart
    stack: echo
    interface: rest
    language: golang
  name: shopping-cart
spec:
  ports:
    - name: http
      port: 9999
      protocol: TCP
      targetPort: 9999
  selector:
    app: shopping-cart