apiVersion: v1
kind: ConfigMap
metadata:
  name: bets-config
data:
  config.json: |
    {
       "name": "bets",
       "version" : "v1",
       "apps": [
         {"name": "matches","url": "http://matches:9999/api/data"},
         {"name": "players","url": "http://players:9999/api/data"},
         {"name": "championships","url": "http://championships:9999/api/data"}
       ]
    }