apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-config
data:
  config.json: |
    {
       "name": "customer",
       "version" : "v1",
       "apps": [
          {"name": "user","url": "http://user:9999/api/data"}
       ]
    }